### ISSUE TITLE
Error: Cannot find module 'autoprefixer' 

### ISSUE THREAD

**Issue by jonjamz** [choonkending/react-webpack-node#177]
After cloning the repository and runing `npm install` and then `npm run dev` I get the following:
```
ERROR in ./~/css-loader?module&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./app/css/main.css
Module build failed: Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.postCSSConfig (/Users/jon/Sites/react-webpack-node/webpack/webpack.config.dev-client.js:44:5)
    at Object.module.exports (/Users/jon/Sites/react-webpack-node/node_modules/postcss-loader/index.js:28:27)
 @ ./app/css/main.css 4:14-179 13:2-17:4 14:20-185
```

**Comment by choonkending** [comment]
@jonjamz Sorry I was just notified of this minutes ago as well. 

I think it might have occured in https://github.com/choonkending/react-webpack-node/pull/172 when I was trying to rebase some of the changes. I'll try to get a fix out during lunch, sit tight!

**Comment by choonkending** [comment]
Really sorry about this one

**Comment by choonkending** [comment]
@jonjamz 
If you're in a rush to get this working, try working from [this](https://github.com/choonkending/react-webpack-node/commit/359932f1c408a3a7d3f6bb7824e324a6cad6b1da) commit. 

I believe updating the packages / css-loader + postcss-loader might cause some weird behavior.

**Comment by choonkending** [comment]
@jonjamz The issue is that we removed the dependency `npm install autoprefixer`. 

That should fix it. I'll push a hotfix when I get the chance. Thanks for raising this issue.

**Comment by jonjamz** [comment]
Yes I was able to fix the problem by running that, thanks!

**Comment by choonkending** [comment]
@jonjamz ^ Fixed. Thanks!

**Comment by puranik3** [comment]
+1
Running ```npm install autoprefixer``` solved the same issue for me too.

**Comment by GGAlanSmithee** [comment]
@puranik3 this should have been fixed in #178 and if you look at [package.json](https://github.com/reactGo/reactGo/blob/master/package.json#L44) autoprefixer is there as a dependency.

Do you have the latest code? If so, this could be a problem with npm's lockfile.

**Comment by talentedaamer** [comment]
@jonjamz @puranik3  whenever you get error "Cannot find module 'xyz'" it means the module is not in "node_modules" directory. so you should run `npm install xyz' this will add the module in your package.json file and also in 'node_modules" directory.

**Comment by justingolden21** [comment]
Just wanted to say that I'm here from a completely unrelated thing (setting up jekyll and tailwind from [this tutorial](https://mdoliwa.com/2020/08/22/how-to-setup-jekyll-with-tailwind-css.html)) and i had the same problem, ran `npm install autoprefixer' and then 'npx tailwindcss init` just worked : )

**Comment by znkhn** [comment]
> Just wanted to say that I'm here from a completely unrelated thing (setting up jekyll and tailwind from [this tutorial](https://mdoliwa.com/2020/08/22/how-to-setup-jekyll-with-tailwind-css.html)) and i had the same problem, ran `npm install autoprefixer' and then 'npx tailwindcss init` just worked : )

This method didn't work for me :)

**Comment by tankita236** [comment]
Still having an issue with running "npx tailwindcss init", even after installing autoprefixed. Please let me know how to resolve it

**Comment by KaliFuckers** [comment]
> Still having an issue with running "npx tailwindcss init", even after installing autoprefixed. Please let me know how to resolve it

Use yarn

**Comment by tankita236** [comment]
> > Still having an issue with running "npx tailwindcss init", even after installing autoprefixed. Please let me know how to resolve it
> 
> Use yarn

It doesn't work in that way. Yet I found the solution and have fixed it.
We need to install old autofixer step and then get npx tailwindcss init once done reinstall and install the recent autofixer

**Comment by rdhassan** [comment]
> @jonjamz The issue is that we removed the dependency `npm install autoprefixer`.
> 
> That should fix it. I'll push a hotfix when I get the chance. Thanks for raising this issue.

Thankyou bro

**Comment by kr1st1nagr03g3r** [comment]
+1
Running npm install autoprefixer solved the same issue for me too. :)

**Comment by Emmet4** [comment]
@choonkending https://reacter.space/questions/implementing-the-autoprefixer-script-into-the-project-created-with-react-create-app

**Comment by samllCharacter** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
